### PR TITLE
Release `v1.3.1`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v1.3.1` release.
Here you can find all related translations changes: [v1.3.0...master](https://github.com/flarum-lang/slovak/compare/v1.3.0...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## v1.3.1

**Aktualizované preklady pre rozšírenia**:

* [`afrux/asirem`](https://github.com/afrux/asirem)
* [`afrux/news-widget`](https://github.com/afrux/news-widget)
* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`clarkwinkelmann/flarum-ext-emojionearea`](https://github.com/clarkwinkelmann/flarum-ext-emojionearea)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/lock`](https://github.com/flarum/lock)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`flarumite/simple-discussion-views`](https://github.com/flarumite/simple-discussion-views)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/custom-footer`](https://github.com/FriendsOfFlarum/custom-footer)
* [`fof/html-errors`](https://github.com/FriendsOfFlarum/html-errors)
* [`glowingblue/password-strength`](https://github.com/glowingblue/flarum-ext-password-strength)
* [`justoverclock/hot-discussions`](https://github.com/justoverclockl/hot-discussions)

Všetky zmeny: [v1.3.0...v1.3.1](https://github.com/flarum-lang/slovak/compare/v1.3.0...v1.3.1).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@SKevo18 Why did you closed this PR?

**Comment by SKevo18** [comment]
I have already tagged a new release after approving the previous PR, as I thought that the tag wasn't created automatically by the bot for some reason - turns out, it was only delayed (if you compare this, you'll see that there are no changes, so this is essentially an empty release). Sorry, haven't used the process in a while. I assume that the next PR will just use 1.3.1 again with actual changes

**Comment by rob006** [comment]
This is 1.3.1 PR with actual changes, and it does not look empty: https://github.com/flarum-lang/slovak/compare/v1.3.0...master. I'm not sure what happened with #5 (1.3.0 release), maybe bot crashed and did not complete release process. But this PR should be fine, so I'm opening it - feel free to approve it whenever you're ready. If bot gets stuck again, and don't complete release, please do not tag release manually and just ping me - I would want to investigate this.

**Comment by rob006** [comment]
Damn, it looks like this problem affects all releases in this repo - not even a single one PR was merged correctly for this language pack (bot should tag release and comment with template of release announcement) so there is definitely something off with bot/repo configuration. :/

**Comment by SKevo18** [comment]
> If bot gets stuck again, and don't complete release, please do not tag release manually and just ping me - I would want to investigate this.

Sure will do! Sorry if I messed the PR up a bit, but hopefully you find out what causes this

**Comment by rob006** [comment]
No worry, it is not your fault - there is something wrong with bot, but I'm not sure what (there are no errors in log, and in fact some expected warnings are missing). I added more logging for queue responsible for merging PRs, I hope it will help me to figure out what is happening.

**Comment by rob006** [comment]
Just to note: I suspect this options was responsible for these problems:

6c885a61

It is disabled now, so I hope this PR will be handled correctly. :crossed_fingers:

**Review by SKevo18 — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/d/20993):

~~~markdown
## Verzia [`v1.3.1`](https://github.com/flarum-lang/slovak/releases/tag/v1.3.1)

**Aktualizované preklady pre rozšírenia**:

* [`afrux/asirem`](https://github.com/afrux/asirem)
* [`afrux/news-widget`](https://github.com/afrux/news-widget)
* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`clarkwinkelmann/flarum-ext-emojionearea`](https://github.com/clarkwinkelmann/flarum-ext-emojionearea)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/lock`](https://github.com/flarum/lock)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`flarumite/simple-discussion-views`](https://github.com/flarumite/simple-discussion-views)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/custom-footer`](https://github.com/FriendsOfFlarum/custom-footer)
* [`fof/html-errors`](https://github.com/FriendsOfFlarum/html-errors)
* [`glowingblue/password-strength`](https://github.com/glowingblue/flarum-ext-password-strength)
* [`justoverclock/hot-discussions`](https://github.com/justoverclockl/hot-discussions)


Všetky zmeny: [v1.3.0...v1.3.1](https://github.com/flarum-lang/slovak/compare/v1.3.0...v1.3.1).

Spustite nasledovné príkazy pre aktualizáciu:

```console
composer update flarum-lang/slovak
php flarum cache:clear
```

~~~

**Comment by rob006** [comment]
:tada:

**Pull request merged**
